### ISSUE TITLE
Please clarify how can I uniquely track my users 

### ISSUE THREAD

**Issue by rturk** [takenet/blip-chat-widget#6]
Our platform can be accessed via multiple channels (App or Web). We would like to improve user experience allowing a chat that started in the web to be finished in the App.

How can I set a unique ID for our users?

We can pass a unique userId is associated with our own userId system.

**Comment by brenoqueiroz** [comment]
You should add your own userId to the extras property in account

**Comment by rturk** [comment]
Blip will account this `userId` when displaying messages and factor this in the context? 
Meaning will the user be able to start a conversation in the browser and finish the app?

**Comment by brenoqueiroz** [comment]
Since you want to use your ID,in your bot u have to query for the account and use this information (ur userid) to keep the user state.

the user wont have the message history in this case, if i start in the web when i change to app the chat will be blank.

**Comment by arthursoas** [comment]
Hi @rturk, since you opened this issue, the BLiP Chat evolved, and your problem has a graceful solution.

You can use the `DEV_AUTH` (see the docs here: https://github.com/takenet/blip-chat-widget/wiki/Authentication-Types) to authenticate your users on any platform (web and app).
You can log a user in using your own `userId` system by filling the field `userIdentity` with it.
You will need also create a password for each user. You must use the same password to authenticate the user at every platforms you have. You can use a hash based on the `userIdentity` for example.

When you log a user in using `DEV_AUTH`, the user will be able to see all the conversation history, independent of from where it is accessing your bot. Remember you need use the same `AppKey` on all of your platforms.
